import type { Release } from "./types";

// Helper function to create dates relative to today
const getRelativeDate = (dayOffset: number): string => {
  const date = new Date();
  date.setDate(date.getDate() + dayOffset);
  return date.toISOString().split("T")[0];
};

export const releases: Release[] = [
  {
    id: "release-1",
    name: "Release 2023.4",
    status: "past",
    color: "#6366F1", // indigo
    steps: [
      {
        id: "r1-step-1",
        name: "Spike",
        description: "Research and exploration of technical solutions",
        startDate: getRelativeDate(-55),
        endDate: getRelativeDate(-50),
        completed: true,
      },
      {
        id: "r1-step-2",
        name: "Design",
        description: "UI/UX design and prototyping",
        startDate: getRelativeDate(-49),
        endDate: getRelativeDate(-45),
        completed: true,
      },
      {
        id: "r1-step-3",
        name: "Requirements",
        description: "Gathering detailed product requirements",
        startDate: getRelativeDate(-44),
        endDate: getRelativeDate(-41),
        completed: true,
      },
      {
        id: "r1-step-4",
        name: "Architecture",
        description: "Defining system architecture and components",
        startDate: getRelativeDate(-40),
        endDate: getRelativeDate(-37),
        completed: true,
      },
      {
        id: "r1-step-5",
        name: "Planning",
        description: "Sprint planning and task breakdown",
        startDate: getRelativeDate(-36),
        endDate: getRelativeDate(-34),
        completed: true,
      },
      {
        id: "r1-step-6",
        name: "Development",
        description: "Implementation of features and functionality",
        startDate: getRelativeDate(-33),
        endDate: getRelativeDate(-27),
        completed: true,
      },
      {
        id: "r1-step-7",
        name: "Testing",
        description: "QA and bug fixing",
        startDate: getRelativeDate(-26),
        endDate: getRelativeDate(-22),
        completed: true,
      },
      {
        id: "r1-step-8",
        name: "Security Audit",
        description: "Security review and vulnerability assessment",
        startDate: getRelativeDate(-24),
        endDate: getRelativeDate(-21),
        completed: true,
      },
      {
        id: "r1-step-9",
        name: "Performance Testing",
        description: "Load testing and optimization",
        startDate: getRelativeDate(-23),
        endDate: getRelativeDate(-20),
        completed: true,
      },
      {
        id: "r1-step-10",
        name: "Documentation",
        description: "Creating user and technical documentation",
        startDate: getRelativeDate(-21),
        endDate: getRelativeDate(-18),
        completed: true,
      },
      {
        id: "r1-step-11",
        name: "User Training",
        description: "Training sessions for end users",
        startDate: getRelativeDate(-19),
        endDate: getRelativeDate(-18),
        completed: true,
      },
      {
        id: "r1-step-12",
        name: "Release",
        description: "Deployment to production",
        startDate: getRelativeDate(-17),
        endDate: getRelativeDate(-17),
        completed: true,
      },
    ],
  },
  {
    id: "release-2",
    name: "Release 2023.5",
    status: "past",
    color: "#8B5CF6", // purple
    steps: [
      {
        id: "r2-step-1",
        name: "Spike",
        description: "Research and exploration of technical solutions",
        startDate: getRelativeDate(-40),
        endDate: getRelativeDate(-35),
        completed: true,
      },
      {
        id: "r2-step-2",
        name: "Design",
        description: "UI/UX design and prototyping",
        startDate: getRelativeDate(-34),
        endDate: getRelativeDate(-30),
        completed: true,
      },
      {
        id: "r2-step-3",
        name: "Requirements",
        description: "Gathering detailed product requirements",
        startDate: getRelativeDate(-29),
        endDate: getRelativeDate(-26),
        completed: true,
      },
      {
        id: "r2-step-4",
        name: "Architecture",
        description: "Defining system architecture and components",
        startDate: getRelativeDate(-25),
        endDate: getRelativeDate(-22),
        completed: true,
      },
      {
        id: "r2-step-5",
        name: "Planning",
        description: "Sprint planning and task breakdown",
        startDate: getRelativeDate(-21),
        endDate: getRelativeDate(-19),
        completed: true,
      },
      {
        id: "r2-step-6",
        name: "Development",
        description: "Implementation of features and functionality",
        startDate: getRelativeDate(-18),
        endDate: getRelativeDate(-12),
        completed: true,
      },
      {
        id: "r2-step-7",
        name: "Testing",
        description: "QA and bug fixing",
        startDate: getRelativeDate(-11),
        endDate: getRelativeDate(-7),
        completed: true,
      },
      {
        id: "r2-step-8",
        name: "Security Audit",
        description: "Security review and vulnerability assessment",
        startDate: getRelativeDate(-9),
        endDate: getRelativeDate(-6),
        completed: true,
      },
      {
        id: "r2-step-9",
        name: "Performance Testing",
        description: "Load testing and optimization",
        startDate: getRelativeDate(-8),
        endDate: getRelativeDate(-5),
        completed: true,
      },
      {
        id: "r2-step-10",
        name: "Documentation",
        description: "Creating user and technical documentation",
        startDate: getRelativeDate(-6),
        endDate: getRelativeDate(-3),
        completed: true,
      },
      {
        id: "r2-step-11",
        name: "User Training",
        description: "Training sessions for end users",
        startDate: getRelativeDate(-4),
        endDate: getRelativeDate(-3),
        completed: true,
      },
      {
        id: "r2-step-12",
        name: "Release",
        description: "Deployment to production",
        startDate: getRelativeDate(-2),
        endDate: getRelativeDate(-2),
        completed: true,
      },
    ],
  },
  {
    id: "release-3",
    name: "Release 2023.6",
    status: "current",
    color: "#EC4899", // pink
    steps: [
      {
        id: "r3-step-1",
        name: "Spike",
        description: "Research and exploration of technical solutions",
        startDate: getRelativeDate(-25),
        endDate: getRelativeDate(-20),
        completed: true,
      },
      {
        id: "r3-step-2",
        name: "Design",
        description: "UI/UX design and prototyping",
        startDate: getRelativeDate(-19),
        endDate: getRelativeDate(-15),
        completed: true,
      },
      {
        id: "r3-step-3",
        name: "Requirements",
        description: "Gathering detailed product requirements",
        startDate: getRelativeDate(-14),
        endDate: getRelativeDate(-11),
        completed: true,
      },
      {
        id: "r3-step-4",
        name: "Architecture",
        description: "Defining system architecture and components",
        startDate: getRelativeDate(-10),
        endDate: getRelativeDate(-7),
        completed: true,
      },
      {
        id: "r3-step-5",
        name: "Planning",
        description: "Sprint planning and task breakdown",
        startDate: getRelativeDate(-6),
        endDate: getRelativeDate(-4),
        completed: true,
      },
      {
        id: "r3-step-6",
        name: "Development",
        description: "Implementation of features and functionality",
        startDate: getRelativeDate(-3),
        endDate: getRelativeDate(3),
        completed: false,
      },
      {
        id: "r3-step-7",
        name: "Testing",
        description: "QA and bug fixing",
        startDate: getRelativeDate(4),
        endDate: getRelativeDate(8),
        completed: false,
      },
      {
        id: "r3-step-8",
        name: "Security Audit",
        description: "Security review and vulnerability assessment",
        startDate: getRelativeDate(6),
        endDate: getRelativeDate(9),
        completed: false,
      },
      {
        id: "r3-step-9",
        name: "Performance Testing",
        description: "Load testing and optimization",
        startDate: getRelativeDate(7),
        endDate: getRelativeDate(10),
        completed: false,
      },
      {
        id: "r3-step-10",
        name: "Documentation",
        description: "Creating user and technical documentation",
        startDate: getRelativeDate(9),
        endDate: getRelativeDate(12),
        completed: false,
      },
      {
        id: "r3-step-11",
        name: "User Training",
        description: "Training sessions for end users",
        startDate: getRelativeDate(11),
        endDate: getRelativeDate(12),
        completed: false,
      },
      {
        id: "r3-step-12",
        name: "Release",
        description: "Deployment to production",
        startDate: getRelativeDate(13),
        endDate: getRelativeDate(13),
        completed: false,
      },
    ],
  },
  {
    id: "release-4",
    name: "Release 2023.7",
    status: "future",
    color: "#10B981", // emerald
    steps: [
      {
        id: "r4-step-1",
        name: "Spike",
        description: "Research and exploration of technical solutions",
        startDate: getRelativeDate(5),
        endDate: getRelativeDate(10),
        completed: false,
      },
      {
        id: "r4-step-2",
        name: "Design",
        description: "UI/UX design and prototyping",
        startDate: getRelativeDate(11),
        endDate: getRelativeDate(15),
        completed: false,
      },
      {
        id: "r4-step-3",
        name: "Requirements",
        description: "Gathering detailed product requirements",
        startDate: getRelativeDate(13),
        endDate: getRelativeDate(16),
        completed: false,
      },
      {
        id: "r4-step-4",
        name: "Architecture",
        description: "Defining system architecture and components",
        startDate: getRelativeDate(15),
        endDate: getRelativeDate(18),
        completed: false,
      },
      {
        id: "r4-step-5",
        name: "Planning",
        description: "Sprint planning and task breakdown",
        startDate: getRelativeDate(16),
        endDate: getRelativeDate(18),
        completed: false,
      },
      {
        id: "r4-step-6",
        name: "Development",
        description: "Implementation of features and functionality",
        startDate: getRelativeDate(19),
        endDate: getRelativeDate(25),
        completed: false,
      },
      {
        id: "r4-step-7",
        name: "Testing",
        description: "QA and bug fixing",
        startDate: getRelativeDate(26),
        endDate: getRelativeDate(30),
        completed: false,
      },
      {
        id: "r4-step-8",
        name: "Security Audit",
        description: "Security review and vulnerability assessment",
        startDate: getRelativeDate(27),
        endDate: getRelativeDate(30),
        completed: false,
      },
      {
        id: "r4-step-9",
        name: "Performance Testing",
        description: "Load testing and optimization",
        startDate: getRelativeDate(28),
        endDate: getRelativeDate(32),
        completed: false,
      },
      {
        id: "r4-step-10",
        name: "Documentation",
        description: "Creating user and technical documentation",
        startDate: getRelativeDate(28),
        endDate: getRelativeDate(32),
        completed: false,
      },
      {
        id: "r4-step-11",
        name: "Release",
        description: "Deployment to production",
        startDate: getRelativeDate(33),
        endDate: getRelativeDate(33),
        completed: false,
      },
    ],
  },
  {
    id: "release-5",
    name: "Release 2023.8",
    status: "future",
    color: "#F59E0B", // amber
    steps: [
      {
        id: "r5-step-1",
        name: "Spike",
        description: "Research and exploration of technical solutions",
        startDate: getRelativeDate(20),
        endDate: getRelativeDate(25),
        completed: false,
      },
      {
        id: "r5-step-2",
        name: "Design",
        description: "UI/UX design and prototyping",
        startDate: getRelativeDate(26),
        endDate: getRelativeDate(30),
        completed: false,
      },
      {
        id: "r5-step-3",
        name: "Planning",
        description: "Sprint planning and task breakdown",
        startDate: getRelativeDate(31),
        endDate: getRelativeDate(33),
        completed: false,
      },
      {
        id: "r5-step-4",
        name: "Development",
        description: "Implementation of features and functionality",
        startDate: getRelativeDate(34),
        endDate: getRelativeDate(40),
        completed: false,
      },
      {
        id: "r5-step-5",
        name: "Testing",
        description: "QA and bug fixing",
        startDate: getRelativeDate(41),
        endDate: getRelativeDate(45),
        completed: false,
      },
      {
        id: "r5-step-6",
        name: "Documentation",
        description: "Creating user and technical documentation",
        startDate: getRelativeDate(43),
        endDate: getRelativeDate(47),
        completed: false,
      },
      {
        id: "r5-step-7",
        name: "Release",
        description: "Deployment to production",
        startDate: getRelativeDate(48),
        endDate: getRelativeDate(48),
        completed: false,
      },
    ],
  },
];
